[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x282c33"
foreground = "0xabb2bf"

[env]
TERM = "xterm-256color"

[font]
# linux laptop
# size = 9.5

# macos
size = 16

[font.offset]
x = 0

# linux laptop
# y = 0

# macos
y = 4

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
# family = "MesloLGS Nerd Font"
style = "Regular"


[keyboard]
bindings = [
  { key = "Return", mods = "Shift", chars = "\u001B[13;2u" },
  { key = "Return", mods = "Control", chars = "\u001B[13;5u" },

  { key = "V", mods = "Super", action = "Paste" },
  { key = "C", mods = "Super", action = "Copy" },
  { key = "V", mods = "Control", action = "ReceiveChar" },

  # panes
  { key = "P", mods = "Command", chars = "\u0001\u0070" },
  { key = "P", mods = "Command|Shift", chars = "\u0001\u0050" },
  { key = "H", mods = "Command", chars = "\u0001\u0008" },
  { key = "H", mods = "Command|Alt", chars = "\u0001\u0068" },
  { key = "J", mods = "Command", chars = "\u0001\u000a" },
  { key = "J", mods = "Command|Alt", chars = "\u0001\u006a" },
  { key = "J", mods = "Command|Shift", chars = "\u0001\u004a" },
  { key = "K", mods = "Command", chars = "\u0001\u000b" },
  { key = "K", mods = "Command|Alt", chars = "\u0001\u006b" },
  { key = "K", mods = "Command|Shift", chars = "\u0001\u004b" },
  { key = "L", mods = "Command", chars = "\u0001\u000c" },
  { key = "L", mods = "Command|Alt", chars = "\u0001\u006c" },

  # windows
  { key = "T", mods = "Command", chars = "\u0001\u0014" },
  { key = "1", mods = "Command", chars = "\u0001\u0031" },
  { key = "2", mods = "Command", chars = "\u0001\u0032" },
  { key = "3", mods = "Command", chars = "\u0001\u0033" },
  { key = "4", mods = "Command", chars = "\u0001\u0034" },
  { key = "5", mods = "Command", chars = "\u0001\u0035" },
  { key = "6", mods = "Command", chars = "\u0001\u0036" },
  { key = "7", mods = "Command", chars = "\u0001\u0037" },
  { key = "8", mods = "Command", chars = "\u0001\u0038" },
  { key = "9", mods = "Command", chars = "\u0001\u0039" },
  { key = "A", mods = "Command", chars = "\u0001\u0001" },

  # break pane into new window
  { key = "T", mods = "Command|Shift", chars = "\u0001\u0074" },

  # sessions
  { key = "S", mods = "Command", chars = "\u0001\u0073" },
  { key = "E", mods = "Command", chars = "\u0001\u0065" },
]


[scrolling]
history = 100000

[window]
decorations = "Buttonless"
opacity = 0.9
startup_mode = "Maximized"
dynamic_padding = true
option_as_alt = "Both"
blur = true

# macos
# [window.padding]
# x = 93

[shell]
program = "/opt/homebrew/bin/tmux"
