# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[â¯â¯â¯](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ—âœ—âœ—](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 100
format = "underwent [$duration](bold yellow)"

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"
truncate_to_repo = false
home_symbol = "ğŸš€"
