# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[â¯â¯â¯](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ—âœ—âœ—](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 10
format = "[$duration](bold yellow)"

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"
truncate_to_repo = false
home_symbol = "_"

[conda]
symbol = "ğŸ "
format = "via [$symbol$environment](bold green) "

[gcloud]
disabled = true
symbol = "ï¸G"
format = '[$symbol(\($region\))]($style) '

[aws]
disabled = true
format = '[$symbol($profile )]($style)'
style = "orange"
symbol = "ğŸ…° "

[kubernetes]
disabled = true
format = '[â›µ $cluster](dimmed green) '

[docker_context]
disabled = true
